const fs = require('fs');
const ts = require('typescript');
const vm = require('vm');
const assert = require('node:assert/strict');
const storage = new Map();
const context = { exports: {}, sessionStorage: { getItem: k => storage.get(k), setItem: (k, v) => storage.set(k, v) } };
const output = ts.transpileModule(fs.readFileSync(require.resolve('../src/utils/pageStores.ts'), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
vm.runInNewContext(output, context);
const api = context.exports;
const a = { Id: 1, Name: 'A', Role: 'worker', Pages: ['workbench'] };
const b = { Id: 2, Name: 'B', Role: 'manager', Pages: ['workbench', 'dashboard'] };
const stores = [a, b];
assert.deepEqual(Array.from(api.getAllowedPages(stores)), ['workbench', 'dashboard']);
assert.deepEqual(Array.from(api.getPageStores(stores, 'dashboard')), [b]);
assert.deepEqual(Array.from(api.getPageStores(stores, 'staff-access')), []);
assert.equal(api.choosePageStore(api.getPageStores(stores, 'dashboard'), 1), b);
assert.equal(api.choosePageStore(stores, 2), b);
assert.equal(api.choosePageStore([], 2), undefined);
api.rememberPageStore(1, 'workbench', 1);
api.rememberPageStore(1, 'dashboard', 2);
assert.equal(api.getPreferredStore(1, 'workbench'), 1);
assert.equal(api.getPreferredStore(1, 'dashboard'), 2);
assert.equal(api.getPreferredStore(2, 'dashboard'), undefined);
// 撤销原先选中门店的页面权限后必须回落到有权限的门店。
assert.equal(api.choosePageStore(api.getPageStores([a], 'workbench'), 2), a);
api.setCurrentStoreId(2);
assert.equal(api.getCurrentStoreId(), 2);
assert.equal(api.getPreferredStore(1, 'workbench'), 1);
console.log('Per-page stores, mixed roles, revocation and independent preference checks passed');
